apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: dc-analytics-certificate
    kubernetes.io/ingress.global-static-ip-name: dc-analytics
  name: dc-analytics
  namespace: iris
spec:
  rules:
  - host: dc-analytics.myardyas.online
    http:
      paths:
      - backend:
          serviceName: dc-analytics
          servicePort: 52773
        path: /*
